"use client";

import { useEffect, useState } from "react";

type Section = "updates" | "tasks" | "events" | "catalogue" | "merch" | "uploads";
type Brand = "kaja" | "hexenwerk" | "virginia";

export function MobileMenu({ brand, view, catalogue }: { brand: Brand; view: Section; catalogue: "live" | "upcoming" | "ideas" }) {
  const [open, setOpen] = useState(false);
  const [catalogueOpen, setCatalogueOpen] = useState(view === "catalogue");
  useEffect(() => { if (!open) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.body.style.overflow = "hidden"; window.addEventListener("keydown", close); return () => { document.body.style.overflow = ""; window.removeEventListener("keydown", close); }; }, [open]);
  const link = (nextBrand: Brand, nextView: Section, group = catalogue) => `/?brand=${nextBrand}&view=${nextView}${nextView === "catalogue" ? `&catalogue=${group}` : ""}`;
  return <div className="mobile-menu"><button className="mobile-menu-button" aria-expanded={open} aria-controls="mobile-navigation" onClick={() => setOpen(true)}>Meniu</button>{open && <><button className="mobile-menu-overlay" aria-label="Închide meniul" onClick={() => setOpen(false)} /><aside className="mobile-drawer" id="mobile-navigation" aria-label="Navigare spațiu de lucru"><div className="mobile-drawer-head"><b>Meniu</b><button className="mobile-close" aria-label="Închide meniul" onClick={() => setOpen(false)}>×</button></div><label className="mobile-drawer-label" htmlFor="brand-picker">Brand</label><select id="brand-picker" className="mobile-brand-picker" value={brand} onChange={(event) => { window.location.href = link(event.target.value as Brand, view); }}><option value="kaja">KAJA</option><option value="hexenwerk">HEXENWERK</option><option value="virginia">VIRGINIA</option></select><div className="mobile-drawer-label mobile-members-label">Membri</div><p className="mobile-members">Patrick · Ionut · Igor · Andrei</p><nav className="mobile-section-list">{(["updates", "tasks", "events", "catalogue", "merch", "uploads"] as Section[]).map((entry) => entry === "catalogue" ? <div key={entry}><button className={view === "catalogue" ? "active" : undefined} onClick={() => setCatalogueOpen(!catalogueOpen)}>Catalog <span>{catalogueOpen ? "−" : "+"}</span></button>{catalogueOpen && <div className="mobile-catalogue-list"><a href={link(brand, "catalogue", "live")} className={view === "catalogue" && catalogue === "live" ? "active" : undefined}>Catalog activ</a><a href={link(brand, "catalogue", "upcoming")} className={view === "catalogue" && catalogue === "upcoming" ? "active" : undefined}>În curând</a><a href={link(brand, "catalogue", "ideas")} className={view === "catalogue" && catalogue === "ideas" ? "active" : undefined}>Idei</a></div>}</div> : <a key={entry} href={link(brand, entry)} className={view === entry ? "active" : undefined}>{({ updates: "Actualizări", tasks: "Sarcini", events: "Evenimente", merch: "Merch", uploads: "Încărcări" } as const)[entry]}</a>)}</nav></aside></>}</div>;
}
