"use client";

import { useEffect, useRef, useState } from "react";

type Section = "updates" | "tasks" | "events" | "catalogue" | "merch" | "uploads";
type Brand = "kaja" | "hexenwerk" | "virginia";
const brandLabels: Record<Brand, string> = { kaja: "KAJA", hexenwerk: "HEXENWERK", virginia: "VIRGINIA" };

export function MobileMenu({ brand, view, catalogue }: { brand: Brand; view: Section; catalogue: "live" | "upcoming" | "ideas" }) {
  const [open, setOpen] = useState(false);
  const [catalogueOpen, setCatalogueOpen] = useState(view === "catalogue");
  const [brandOpen, setBrandOpen] = useState(false);
  const [memberName, setMemberName] = useState("Membru");
  const brandControl = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!open) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") { setOpen(false); setBrandOpen(false); } }; document.body.style.overflow = "hidden"; window.addEventListener("keydown", close); return () => { document.body.style.overflow = ""; window.removeEventListener("keydown", close); }; }, [open]);
  useEffect(() => { const close = (event: PointerEvent) => { if (brandControl.current && !brandControl.current.contains(event.target as Node)) setBrandOpen(false); }; document.addEventListener("pointerdown", close); return () => document.removeEventListener("pointerdown", close); }, []);
  useEffect(() => { setMemberName(document.querySelector(".workspace-brand .identity")?.textContent?.trim() || "Membru"); }, []);
  const link = (nextBrand: Brand, nextView: Section, group = catalogue) => `/?brand=${nextBrand}&view=${nextView}${nextView === "catalogue" ? `&catalogue=${group}` : ""}`;
  return <div className="mobile-menu"><button className="mobile-menu-button" aria-expanded={open} aria-controls="mobile-navigation" onClick={() => setOpen(true)}>Meniu</button>{open && <><button className="mobile-menu-overlay" aria-label="Închide meniul" onClick={() => setOpen(false)} /><aside className="mobile-drawer" id="mobile-navigation" aria-label="Navigare spațiu de lucru"><div className="mobile-drawer-head"><b>Meniu</b><button className="mobile-close" aria-label="Închide meniul" onClick={() => setOpen(false)}>×</button></div><div className="mobile-member-identity"><span className="dot" /> {memberName}</div><div className="mobile-drawer-label">Brand</div><div className="mobile-brand-control" ref={brandControl}><button className="mobile-brand-trigger" aria-expanded={brandOpen} aria-haspopup="listbox" onClick={() => setBrandOpen(!brandOpen)}>{brandLabels[brand]}<span aria-hidden="true">{brandOpen ? "↑" : "↓"}</span></button>{brandOpen && <div className="mobile-brand-options" role="listbox" aria-label="Selectează brandul">{(Object.keys(brandLabels) as Brand[]).map((entry) => <a key={entry} role="option" aria-selected={brand === entry} className={brand === entry ? "active" : undefined} href={link(entry, view)} onClick={() => setBrandOpen(false)}>{brandLabels[entry]}<span>{brand === entry ? "●" : ""}</span></a>)}</div>}</div><nav className="mobile-section-list">{(["updates", "tasks", "events", "catalogue", "merch", "uploads"] as Section[]).map((entry) => entry === "catalogue" ? <div key={entry}><button className={view === "catalogue" ? "active" : undefined} onClick={() => setCatalogueOpen(!catalogueOpen)}>Catalog <span>{catalogueOpen ? "−" : "+"}</span></button>{catalogueOpen && <div className="mobile-catalogue-list"><a href={link(brand, "catalogue", "live")} className={view === "catalogue" && catalogue === "live" ? "active" : undefined}>Catalog activ</a><a href={link(brand, "catalogue", "upcoming")} className={view === "catalogue" && catalogue === "upcoming" ? "active" : undefined}>În curând</a><a href={link(brand, "catalogue", "ideas")} className={view === "catalogue" && catalogue === "ideas" ? "active" : undefined}>Idei</a></div>}</div> : <a key={entry} href={link(brand, entry)} className={view === entry ? "active" : undefined}>{({ updates: "Actualizări", tasks: "Sarcini", events: "Evenimente", merch: "Merch", uploads: "Încărcări" } as const)[entry]}</a>)}</nav></aside></>}</div>;
}
