import Image from "next/image";
import type { ReactNode } from "react";
import { currentMember } from "../lib/auth";
import { hasDatabase } from "../lib/db";
import { workspaceItems } from "../lib/schema";
import { createComment, createTask, createUpdate, createWorkspaceItem, deleteAttachment, deleteComment, deleteRecord, deleteWorkspaceItem, editUpdate, updateTask, updateWorkspaceItem, workspaceData } from "./actions";
import { MerchComposer } from "./merch-composer";
import { MobileMenu } from "./mobile-menu";
import { PdfUploader } from "./pdf-uploader";
import { WelcomeIntro } from "./welcome-intro";

export const dynamic = "force-dynamic";
const sections = [{ key: "updates", label: "Actualizări" }, { key: "tasks", label: "Sarcini" }, { key: "events", label: "Evenimente" }, { key: "catalogue", label: "Catalog" }, { key: "merch", label: "Merch" }, { key: "uploads", label: "Încărcări" }] as const;
const brands = [{ key: "kaja", label: "KAJA" }, { key: "hexenwerk", label: "HEXENWERK" }, { key: "virginia", label: "VIRGINIA" }] as const;
const catalogueGroups = [{ key: "live", label: "Catalog activ" }, { key: "upcoming", label: "În curând" }, { key: "ideas", label: "Idei" }] as const;
type Section = (typeof sections)[number]["key"];
type Brand = (typeof brands)[number]["key"];
type CatalogueGroup = (typeof catalogueGroups)[number]["key"];
type Data = NonNullable<Awaited<ReturnType<typeof workspaceData>>>;
type WorkspaceItemRow = { item: typeof workspaceItems.$inferSelect; author: string };
type CommentRow = Data["comments"][number];

function date(value: Date) { return new Intl.DateTimeFormat("ro-RO", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "Europe/Chisinau" }).format(value); }
function fileSize(bytes: number) { return bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }
function Composer({ label, children }: { label: string; children: ReactNode }) { return <details className="composer-toggle"><summary>{label}</summary><div className="composer-content">{children}</div></details>; }
function Comments({ brand, entityType, entityId, comments, memberSlug }: { brand: Brand; entityType: "update" | "task" | "events" | "catalogue" | "merch"; entityId: number; comments: CommentRow[]; memberSlug: string }) {
  const own = comments.filter(({ comment }) => comment.entityType === entityType && comment.entityId === entityId);
  return <details className="comments"><summary>Comentarii ({own.length})</summary><div className="comment-list">{own.map(({ comment, author, authorSlug }) => <div className="comment" key={comment.id}><div><b>{author}</b><span>{date(comment.createdAt)}</span></div><p>{comment.body}</p>{authorSlug === memberSlug && <form action={deleteComment}><input type="hidden" name="id" value={comment.id} /><input type="hidden" name="brand" value={brand} /><input type="hidden" name="entityType" value={entityType} /><input type="hidden" name="entityId" value={entityId} /><button className="text-button danger">Șterge comentariul</button></form>}</div>)}</div><form action={createComment} className="comment-form"><input type="hidden" name="brand" value={brand} /><input type="hidden" name="entityType" value={entityType} /><input type="hidden" name="entityId" value={entityId} /><textarea name="body" required maxLength={1000} placeholder="Scrie un comentariu" /><button className="button">Comentează</button></form></details>;
}
function EntryCard({ brand, type, id, title, body, author, comments, memberSlug, immutable = false }: { brand: Brand; type: "update" | "task" | "events" | "catalogue" | "merch"; id: number; title: string; body?: string; author: string; comments: CommentRow[]; memberSlug: string; immutable?: boolean }) {
  return <article id={`entry-${type}-${id}`} className="item card"><h3 className="item-title">{title}</h3>{body && <p>{body}</p>}<div className="meta"><span>Creat de {author}</span></div><Comments brand={brand} entityType={type} entityId={id} comments={comments} memberSlug={memberSlug} />{immutable && <form action={deleteWorkspaceItem} className="edit-form"><input type="hidden" name="id" value={id} /><input type="hidden" name="brand" value={brand} /><input type="hidden" name="section" value="merch" /><input type="hidden" name="title" value={title} /><button className="button ghost danger">Șterge produsul merch</button></form>}</article>;
}
function WorkspaceSection({ brand, section, title, items, comments, memberSlug, catalogueGroup }: { brand: Brand; section: "events" | "catalogue" | "merch"; title: string; items: WorkspaceItemRow[]; comments: CommentRow[]; memberSlug: string; catalogueGroup?: CatalogueGroup }) {
  const label = section === "catalogue" ? "produs din catalog" : title.toLowerCase();
  const toggleLabel = section === "merch" ? "Adaugă produs merch" : `Adaugă ${label}`;
  const canCreate = memberSlug === "patrick" || (section !== "merch" && (section !== "catalogue" || catalogueGroup === "ideas"));
  const composer = section === "merch" ? <MerchComposer brand={brand} /> : <form action={createWorkspaceItem} className="form"><input type="hidden" name="brand" value={brand} /><input type="hidden" name="section" value={section} />{catalogueGroup && <input type="hidden" name="catalogueGroup" value={catalogueGroup} />}<input name="title" required maxLength={160} placeholder={`Titlu ${label}`} /><textarea name="body" required maxLength={4000} placeholder={`Descrie ${label}.`} /><button className="button">Adaugă</button></form>;
  return <section className="panel"><div className="panel-head"><h2>{title}</h2><span className="count">{items.length} active</span></div>{canCreate && <Composer label={toggleLabel}>{composer}</Composer>}<div className="items card-grid">{items.map(({ item, author }) => <div key={item.id} className="card-wrap">{section === "merch" && item.merchImageUrl && <img className="merch-preview" src={`/api/merch-images/${item.id}`} alt={`Previzualizare ${item.title}`} />}<EntryCard brand={brand} type={section} id={item.id} title={item.title} body={item.body} author={author} comments={comments} memberSlug={memberSlug} immutable={section === "merch"} />{section !== "merch" && <details className="card-edit"><summary>Editează</summary><form action={updateWorkspaceItem} className="form edit-form"><input type="hidden" name="id" value={item.id} /><input type="hidden" name="brand" value={brand} /><input type="hidden" name="section" value={section} /><input name="title" defaultValue={item.title} required maxLength={160} /><textarea name="body" defaultValue={item.body} required maxLength={4000} /><button className="button">Salvează modificările</button></form><form action={deleteWorkspaceItem} className="edit-form"><input type="hidden" name="id" value={item.id} /><input type="hidden" name="brand" value={brand} /><input type="hidden" name="section" value={section} /><input type="hidden" name="title" value={item.title} /><button className="button ghost danger">Șterge</button></form></details>}</div>)}</div></section>;
}
function UpdatesSection({ brand, data, memberSlug }: { brand: Brand; data: Data; memberSlug: string }) { return <section className="panel"><div className="panel-head"><h2>Actualizări</h2><span className="count">{data.updates.length} active</span></div><Composer label="Adaugă actualizare"><form action={createUpdate} className="form"><input type="hidden" name="brand" value={brand} /><input name="title" required maxLength={160} placeholder="Titlu actualizare" /><textarea name="body" required maxLength={4000} placeholder="Spune ce s-a schimbat și ce urmează." /><button className="button">Publică actualizarea</button></form></Composer><div className="items card-grid">{data.updates.map(({ update, author }) => <div className="card-wrap" key={update.id}><EntryCard brand={brand} type="update" id={update.id} title={update.title} body={update.body} author={author} comments={data.comments} memberSlug={memberSlug} /><details className="card-edit"><summary>Editează actualizarea</summary><form action={editUpdate} className="form edit-form"><input type="hidden" name="id" value={update.id} /><input type="hidden" name="brand" value={brand} /><input name="title" defaultValue={update.title} required maxLength={160} /><textarea name="body" defaultValue={update.body} required maxLength={4000} /><button className="button">Salvează modificările</button></form><form action={deleteRecord} className="edit-form"><input type="hidden" name="id" value={update.id} /><input type="hidden" name="brand" value={brand} /><input type="hidden" name="type" value="update" /><input type="hidden" name="title" value={update.title} /><button className="button ghost danger">Șterge actualizarea</button></form></details></div>)}</div></section>; }
function TasksSection({ brand, data, memberSlug }: { brand: Brand; data: Data; memberSlug: string }) { return <section className="panel"><div className="panel-head"><h2>Sarcini</h2><span className="count">{data.tasks.length} active</span></div><Composer label="Adaugă sarcină"><form action={createTask} className="form compact"><input type="hidden" name="brand" value={brand} /><input name="title" required maxLength={160} placeholder="Adaugă o sarcină" /><button className="button">Adaugă sarcina</button></form></Composer><div className="items card-grid">{data.tasks.map(({ task, author }) => <div className="card-wrap" key={task.id}><EntryCard brand={brand} type="task" id={task.id} title={task.title} author={author} comments={data.comments} memberSlug={memberSlug} /><details className="card-edit"><summary>Editează sarcina</summary><form action={updateTask} className="form edit-form"><input type="hidden" name="id" value={task.id} /><input type="hidden" name="brand" value={brand} /><input name="title" defaultValue={task.title} required maxLength={160} /><button className="button">Salvează sarcina</button></form><form action={deleteRecord} className="edit-form"><input type="hidden" name="id" value={task.id} /><input type="hidden" name="brand" value={brand} /><input type="hidden" name="type" value="task" /><input type="hidden" name="title" value={task.title} /><button className="button ghost danger">Șterge sarcina</button></form></details></div>)}</div></section>; }
function Activity({ data }: { data: Data }) { const target = (type: string, id: number, brand: Brand) => { if (type === "update") { const entry = data.updates.find(({ update }) => update.id === id)?.update; return entry && { title: entry.title, href: `/?brand=${brand}&view=updates#entry-update-${id}` }; } if (type === "task") { const entry = data.tasks.find(({ task }) => task.id === id)?.task; return entry && { title: entry.title, href: `/?brand=${brand}&view=tasks#entry-task-${id}` }; } if (type === "attachment") { const entry = data.attachments.find(({ attachment }) => attachment.id === id)?.attachment; return entry && { title: entry.filename, href: `/?brand=${brand}&view=uploads#attachment-${id}` }; } const entry = data.workspaceItems.find(({ item }) => item.id === id && item.section === type)?.item; if (!entry) return null; const catalogue = entry.section === "catalogue" ? `&catalogue=${entry.catalogueGroup || "live"}` : ""; return { title: entry.title, href: `/?brand=${brand}&view=${entry.section}${catalogue}#entry-${entry.section}-${id}` }; }; return <aside className="panel activity-panel"><div className="panel-head"><h2>Activitate</h2><span className="count">Ultimele 100 acțiuni</span></div><div className="activity">{data.activity.map(({ event, actor }) => { const entry = ["commented", "created", "uploaded"].includes(event.action) ? target(event.entityType, event.entityId, event.brand as Brand) : null; return <div className="event" key={event.id}><b>{actor}</b> {entry ? <a className="activity-link" href={entry.href}>{event.action === "commented" ? `a comentat la ${entry.title}` : event.action === "uploaded" ? `a încărcat ${entry.title}` : `a creat ${entry.title}`}</a> : event.summary}</div>; })}</div></aside>; }
function CatalogueSection({ brand, data, memberSlug, group }: { brand: Brand; data: Data; memberSlug: string; group: CatalogueGroup }) { const active = catalogueGroups.find((entry) => entry.key === group)!; return <><nav className="catalogue-submenu" aria-label="Grupe catalog">{catalogueGroups.map((entry) => <a key={entry.key} className={entry.key === group ? "active" : undefined} href={`/?brand=${brand}&view=catalogue&catalogue=${entry.key}`}>{entry.label}</a>)}</nav><WorkspaceSection brand={brand} section="catalogue" title={active.label} catalogueGroup={group} items={data.workspaceItems.filter(({ item }) => item.section === "catalogue" && item.catalogueGroup === group)} comments={data.comments} memberSlug={memberSlug} /></>; }
function UploadsSection({ brand, data }: { brand: Brand; data: Data }) { return <section className="panel"><div className="panel-head"><h2>Încărcări</h2><span className="count">{data.attachments.length} PDF-uri</span></div><Composer label="Încarcă PDF"><PdfUploader brand={brand} /></Composer><div className="items">{data.attachments.map(({ attachment, author }) => <article id={`attachment-${attachment.id}`} key={attachment.id} className="item attachment"><div><h3 className="item-title">{attachment.filename}</h3><div className="meta"><span>Încărcat de {author}</span><span>·</span><span>{fileSize(attachment.size)}</span></div></div><div className="attachment-actions"><a className="button ghost" href={`/api/attachments/${attachment.id}`}>Descarcă PDF</a><form action={deleteAttachment}><input type="hidden" name="id" value={attachment.id} /><input type="hidden" name="brand" value={brand} /><input type="hidden" name="filename" value={attachment.filename} /><button className="button ghost danger">Șterge</button></form></div></article>)}</div></section>; }
export default async function Home({ searchParams }: { searchParams: Promise<{ view?: string; brand?: string; catalogue?: string }> }) { const member = await currentMember(); if (!member) return <main className="landing"><section className="landing-card"><Image className="logo" src="/kaja-logo.png" alt="KAJA" width={1024} height={240} priority /><p className="eyebrow">Platformă internă pentru membri</p><h1>O imagine comună asupra muncii.</h1><p>Folosește linkul personal KAJA pentru a intra în spațiul de lucru.</p>{!hasDatabase && <div className="setup">Configurarea bazei de date este în așteptare.</div>}</section></main>; const params = await searchParams; const brand: Brand = brands.some((entry) => entry.key === params.brand) ? params.brand as Brand : "kaja"; const view: Section = sections.some((entry) => entry.key === params.view) ? params.view as Section : "tasks"; const group: CatalogueGroup = catalogueGroups.some((entry) => entry.key === params.catalogue) ? params.catalogue as CatalogueGroup : "live"; const data = await workspaceData(brand); if (!data) return <main className="landing">Este necesară baza de date.</main>; const sectionItems = data.workspaceItems.filter(({ item }) => item.section === view); const content = view === "updates" ? <><UpdatesSection brand={brand} data={data} memberSlug={member.slug} /><Activity data={data} /></> : view === "tasks" ? <TasksSection brand={brand} data={data} memberSlug={member.slug} /> : view === "catalogue" ? <CatalogueSection brand={brand} data={data} memberSlug={member.slug} group={group} /> : view === "uploads" ? <UploadsSection brand={brand} data={data} /> : <WorkspaceSection brand={brand} section={view} title={sections.find((entry) => entry.key === view)!.label} items={sectionItems} comments={data.comments} memberSlug={member.slug} />; return <><WelcomeIntro memberName={member.name} memberSlug={member.slug} /><main className="workspace-shell"><header className="workspace-header"><div className="workspace-brand"><Image className="logo" src="/kaja-logo.png" alt="KAJA" width={1024} height={240} priority /><div className="identity"><span className="dot" /> {member.name}</div></div><nav className="brand-switcher" aria-label="Spații de brand">{brands.map((entry) => <a key={entry.key} href={`/?brand=${entry.key}&view=${view}${view === "catalogue" ? `&catalogue=${group}` : ""}`} className={brand === entry.key ? "active" : undefined}>{entry.label}</a>)}</nav><nav className="workspace-nav" aria-label="Secțiuni de lucru">{sections.map((entry) => <a key={entry.key} href={`/?brand=${brand}&view=${entry.key}${entry.key === "catalogue" ? `&catalogue=${group}` : ""}`} className={view === entry.key ? "active" : undefined}>{entry.label}</a>)}</nav></header><MobileMenu brand={brand} view={view} catalogue={group} /><div className="workspace-content">{content}</div></main></>; }
