import Image from "next/image";
import { currentMember } from "../lib/auth";
import { hasDatabase } from "../lib/db";
import { workspaceItems } from "../lib/schema";
import { createTask, createUpdate, createWorkspaceItem, deleteAttachment, deleteRecord, deleteWorkspaceItem, editUpdate, updateTask, updateWorkspaceItem, workspaceData } from "./actions";
import { MerchComposer } from "./merch-composer";
import { PdfUploader } from "./pdf-uploader";
import { WelcomeIntro } from "./welcome-intro";

export const dynamic = "force-dynamic";

const sections = [
  { key: "updates", label: "Updates" }, { key: "tasks", label: "Tasks" }, { key: "events", label: "Events" }, { key: "flavors", label: "Flavors" }, { key: "catalogue", label: "Catalogue" }, { key: "merch", label: "Merch" }, { key: "uploads", label: "Uploads" },
] as const;
const brands = [{ key: "kaja", label: "KAJA" }, { key: "hexenwerk", label: "HEXENWERK" }] as const;
const catalogueGroups = [{ key: "live", label: "Live Catalogue" }, { key: "upcoming", label: "Upcoming" }, { key: "ideas", label: "Ideas" }] as const;
type Section = (typeof sections)[number]["key"];
type Brand = (typeof brands)[number]["key"];
type CatalogueGroup = (typeof catalogueGroups)[number]["key"];
type Data = NonNullable<Awaited<ReturnType<typeof workspaceData>>>;
type WorkspaceItemRow = { item: typeof workspaceItems.$inferSelect; author: string };

function date(value: Date) { return new Intl.DateTimeFormat("en", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "Europe/Chisinau" }).format(value); }
function fileSize(bytes: number) { return bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }

function WorkspaceSection({ brand, section, title, items, catalogueGroup }: { brand: Brand; section: "events" | "flavors" | "catalogue" | "merch"; title: string; items: WorkspaceItemRow[]; catalogueGroup?: CatalogueGroup }) {
  const itemLabel = section === "catalogue" ? "catalogue item" : title.slice(0, -1).toLowerCase();
  return <section className="panel"><div className="panel-head"><h2>{title}</h2><span className="count">{items.length} active</span></div>
    {section === "merch" ? <MerchComposer brand={brand} /> : <form action={createWorkspaceItem} className="form"><input type="hidden" name="brand" value={brand} /><input type="hidden" name="section" value={section} />{catalogueGroup && <input type="hidden" name="catalogueGroup" value={catalogueGroup} />}<input name="title" required maxLength={160} placeholder={`${itemLabel[0]!.toUpperCase()}${itemLabel.slice(1)} title`} /><textarea name="body" required maxLength={4000} placeholder={`Describe this ${itemLabel}.`} /><button className="button">Add {itemLabel}</button></form>}
    <div className="items">{items.map(({ item, author }) => <article key={item.id} className="item">
      {section === "merch" && item.merchImageUrl && <img className="merch-preview" src={`/api/merch-images/${item.id}`} alt={`${item.title} preview`} />}
      <h3 className="item-title">{item.title}</h3><p>{item.body}</p><div className="meta"><span>Created by {author}</span><span>·</span><span>{date(item.updatedAt)}</span></div>
      {section === "merch" ? <form action={deleteWorkspaceItem} className="edit-form"><input type="hidden" name="id" value={item.id} /><input type="hidden" name="brand" value={brand} /><input type="hidden" name="section" value={section} /><input type="hidden" name="title" value={item.title} /><button className="button ghost danger">Delete merch item</button></form> : <details><summary>Edit {itemLabel}</summary><form action={updateWorkspaceItem} className="form edit-form"><input type="hidden" name="id" value={item.id} /><input type="hidden" name="brand" value={brand} /><input type="hidden" name="section" value={section} /><input name="title" defaultValue={item.title} required maxLength={160} /><textarea name="body" defaultValue={item.body} required maxLength={4000} /><button className="button">Save changes</button></form><form action={deleteWorkspaceItem} className="edit-form"><input type="hidden" name="id" value={item.id} /><input type="hidden" name="brand" value={brand} /><input type="hidden" name="section" value={section} /><input type="hidden" name="title" value={item.title} /><button className="button ghost danger">Delete {itemLabel}</button></form></details>}
    </article>)}</div></section>;
}

function UpdatesSection({ brand, data }: { brand: Brand; data: Data }) { return <section className="panel"><div className="panel-head"><h2>Updates</h2><span className="count">{data.updates.length} active</span></div><form action={createUpdate} className="form"><input type="hidden" name="brand" value={brand} /><input name="title" required maxLength={160} placeholder="Update title" /><textarea name="body" required maxLength={4000} placeholder="Share what changed, what matters, or what is next." /><button className="button">Publish update</button></form><div className="items">{data.updates.map(({ update, author }) => <article key={update.id} className="item"><h3 className="item-title">{update.title}</h3><p>{update.body}</p><div className="meta"><span>Created by {author}</span><span>·</span><span>{date(update.updatedAt)}</span></div><details><summary>Edit update</summary><form action={editUpdate} className="form edit-form"><input type="hidden" name="id" value={update.id} /><input type="hidden" name="brand" value={brand} /><input name="title" defaultValue={update.title} required maxLength={160} /><textarea name="body" defaultValue={update.body} required maxLength={4000} /><button className="button">Save changes</button></form><form action={deleteRecord} className="edit-form"><input type="hidden" name="id" value={update.id} /><input type="hidden" name="brand" value={brand} /><input type="hidden" name="type" value="update" /><input type="hidden" name="title" value={update.title} /><button className="button ghost danger">Delete update</button></form></details></article>)}</div></section>; }

function TasksSection({ brand, data }: { brand: Brand; data: Data }) { return <section className="panel"><div className="panel-head"><h2>Tasks</h2><span className="count">{data.tasks.length} active</span></div><form action={createTask} className="form compact"><input type="hidden" name="brand" value={brand} /><input name="title" required maxLength={160} placeholder="Add a task" /><button className="button">Add task</button></form><div className="items">{data.tasks.length === 0 ? <p className="empty">No tasks yet. Turn work into something visible.</p> : data.tasks.map(({ task, author }) => <article key={task.id} className="item"><h3 className="item-title">{task.title}</h3><div className="meta"><span>Created by {author}</span><span>·</span><span>{date(task.updatedAt)}</span></div><details><summary>Edit task</summary><form action={updateTask} className="form edit-form"><input type="hidden" name="id" value={task.id} /><input type="hidden" name="brand" value={brand} /><input name="title" defaultValue={task.title} required maxLength={160} /><button className="button">Save task</button></form><form action={deleteRecord} className="edit-form"><input type="hidden" name="id" value={task.id} /><input type="hidden" name="brand" value={brand} /><input type="hidden" name="type" value="task" /><input type="hidden" name="title" value={task.title} /><button className="button ghost danger">Delete task</button></form></details></article>)}</div></section>; }

function CatalogueSection({ brand, data }: { brand: Brand; data: Data }) { return <div className="catalogue-grid">{catalogueGroups.map((group) => <WorkspaceSection key={group.key} brand={brand} section="catalogue" title={group.label} catalogueGroup={group.key} items={data.workspaceItems.filter(({ item }) => item.section === "catalogue" && item.catalogueGroup === group.key)} />)}</div>; }
function UploadsSection({ brand, data }: { brand: Brand; data: Data }) { return <section className="panel"><div className="panel-head"><h2>Uploads</h2><span className="count">{data.attachments.length} PDFs</span></div><PdfUploader brand={brand} /><div className="items">{data.attachments.map(({ attachment, author }) => <article key={attachment.id} className="item attachment"><div><h3 className="item-title">{attachment.filename}</h3><div className="meta"><span>Uploaded by {author}</span><span>·</span><span>{date(attachment.createdAt)}</span><span>·</span><span>{fileSize(attachment.size)}</span></div></div><div className="attachment-actions"><a className="button ghost" href={`/api/attachments/${attachment.id}`}>Download PDF</a><form action={deleteAttachment}><input type="hidden" name="id" value={attachment.id} /><input type="hidden" name="brand" value={brand} /><input type="hidden" name="filename" value={attachment.filename} /><button className="button ghost danger">Delete</button></form></div></article>)}</div></section>; }

export default async function Home({ searchParams }: { searchParams: Promise<{ view?: string; brand?: string }> }) {
  const member = await currentMember();
  if (!member) return <main className="landing"><section className="landing-card"><Image className="logo" src="/kaja-logo.png" alt="KAJA" width={1024} height={240} priority /><p className="eyebrow">Internal member platform</p><h1>One shared view of the work.</h1><p>Use your personal KAJA link to enter the workspace. Every update, task, and change is attributed to the member who made it.</p>{!hasDatabase && <div className="setup">Database setup is pending. Add the Neon Marketplace integration in Vercel and configure <code>DATABASE_URL</code> before sharing member links.</div>}</section></main>;
  const params = await searchParams;
  const brandName: Brand = brands.some((entry) => entry.key === params.brand) ? params.brand as Brand : "kaja";
  const requestedView = params.view;
  const view: Section = sections.some((section) => section.key === requestedView) ? requestedView as Section : "tasks";
  const data = await workspaceData(brandName);
  if (!data) return <main className="landing"><section className="landing-card"><Image className="logo" src="/kaja-logo.png" alt="KAJA" width={1024} height={240} priority /><h1>Database required.</h1><p>Connect Neon in the Vercel Marketplace, set DATABASE_URL, then deploy again.</p></section></main>;
  const sectionItems = data.workspaceItems.filter(({ item }) => item.section === view);
  const content = view === "updates" ? <UpdatesSection brand={brandName} data={data} /> : view === "tasks" ? <TasksSection brand={brandName} data={data} /> : view === "catalogue" ? <CatalogueSection brand={brandName} data={data} /> : view === "uploads" ? <UploadsSection brand={brandName} data={data} /> : <WorkspaceSection brand={brandName} section={view} title={sections.find((section) => section.key === view)!.label} items={sectionItems} />;
  return <><WelcomeIntro memberName={member.name} memberSlug={member.slug} /><main className="workspace-shell"><header className="workspace-header"><div className="workspace-brand"><Image className="logo" src="/kaja-logo.png" alt="KAJA" width={1024} height={240} priority /><div className="identity"><span className="dot" /> {member.name}</div></div><nav className="brand-switcher" aria-label="Brand workspaces">{brands.map((entry) => <a key={entry.key} href={`/?brand=${entry.key}&view=${view}`} aria-current={brandName === entry.key ? "page" : undefined} className={brandName === entry.key ? "active" : undefined}>{entry.label}</a>)}</nav><nav className="workspace-nav" aria-label="Workspace sections">{sections.map((section) => <a key={section.key} href={`/?brand=${brandName}&view=${section.key}`} aria-current={view === section.key ? "page" : undefined} className={view === section.key ? "active" : undefined}>{section.label}</a>)}</nav></header><div className="workspace-content"><div className="workspace-main">{content}</div><aside className="panel activity-panel"><div className="panel-head"><h2>Activity</h2><span className="count">Last 100 actions</span></div><div className="activity">{data.activity.length === 0 ? <p className="empty">Changes made by the team will appear here.</p> : data.activity.map(({ event, actor }) => <div className="event" key={event.id}><b>{actor}</b> {event.summary}<div className="meta">{date(event.createdAt)}</div></div>)}</div></aside></div></main></>;
}
